import Testing
import Foundation
import UniformTypeIdentifiers
@testable import Yourly

// What leaves the app when somebody taps Share.
//
// The contract is short: two representations of one note, both generated by the exporter the
// pasteboard already uses, and neither of them capable of changing the note. Sharing a note is not the
// Pro Export & Restore feature — it is Copy with a destination attached — so everything Copy already
// guarantees has to hold here too, including the UTF-8 fix that keeps an em dash from arriving as
// "â€”".
@MainActor
struct NoteSharePayloadTests {

    // MARK: Title and body

    @Test func aTitledNoteLeadsWithItsTitle() {
        let payload = NoteSharePayload.make(title: "Trip Plan", body: "Anchorage → Seward → Denali")
        #expect(payload?.title == "Trip Plan")
        #expect(payload?.plainText == "Trip Plan\n\nAnchorage → Seward → Denali")
    }

    @Test func anUntitledNoteSendsItsBodyAndNothingElse() {
        // Emphatically not the word "Title". That is what an empty field *draws* to invite one, and
        // shipping it would be the interface leaking into somebody's message.
        let payload = NoteSharePayload.make(title: nil, body: "Just the note")
        #expect(payload?.title == nil)
        #expect(payload?.plainText == "Just the note")
        #expect(payload?.plainText.contains("Title") == false)
    }

    @Test func aTitleOfNothingButSpacesIsNoTitle() {
        let payload = NoteSharePayload.make(title: "   ", body: "Words")
        #expect(payload?.title == nil)
        #expect(payload?.plainText == "Words")
    }

    @Test func aTitleWithNoBodyIsStillWorthSharing() {
        let payload = NoteSharePayload.make(title: "Trip Plan", body: "")
        #expect(payload?.plainText == "Trip Plan", "a titled note with no body sent a trailing blank")
    }

    // MARK: Nothing to share

    @Test func anEmptyNoteHasNoPayload() {
        #expect(NoteSharePayload.make(title: nil, body: "") == nil)
        #expect(NoteSharePayload.make(title: "", body: "   \n\n  ") == nil)
    }

    @Test func aNoteOfNothingButAMarkerHasNoPayload() {
        // The same test `Note.isEmptyDraft` applies: an abandoned "- " is a note somebody started, not
        // a note somebody wrote. Share must be disabled for it, and this is what disables it.
        #expect(NoteSharePayload.make(title: nil, body: "- ") == nil)
        #expect(NoteSharePayload.make(title: nil, body: "# ") == nil)
    }

    @Test func oneRealCharacterIsEnough() {
        #expect(NoteSharePayload.make(title: nil, body: "- Eggs") != nil)
    }

    // MARK: The page as it reads

    @Test func markersTravelAsTheGlyphsTheyDraw() {
        // The plain flavor is the page as it *reads*, exactly as a copy is — not the source it is
        // stored as. Nobody wants "- [ ] Call Ravi" in a message.
        let payload = NoteSharePayload.make(title: nil, body: "- Eggs\n- [ ] Call Ravi")
        #expect(payload?.plainText.contains("• Eggs") == true)
        #expect(payload?.plainText.contains("☐ Call Ravi") == true)
        #expect(payload?.plainText.contains("- [ ]") == false)
    }

    @Test func aLinkTravelsAsItsWordsInPlainTextAndItsAddressInHTML() {
        let body = "Booking is at [Open reservation](https://astold.app)"
        let payload = NoteSharePayload.make(title: nil, body: body)
        // Characters: the words, with none of the syntax that stores the destination.
        #expect(payload?.plainText.contains("Open reservation") == true)
        #expect(payload?.plainText.contains("](") == false)
        // HTML: a real anchor, which is the whole reason the rich half exists.
        #expect(payload?.html?.contains("<a href=\"https://astold.app\">Open reservation</a>") == true)
    }

    @Test func codeKeepsItsIndentationInsideAPre() {
        let body = "```python\ndef hello():\n    print(\"hi\")\n```"
        let payload = NoteSharePayload.make(title: nil, body: body)
        #expect(payload?.html?.contains("<pre>") == true)
        #expect(payload?.html?.contains("    print(") == true, "the indentation did not survive")
        // And the fences are storage, so they never leave the app as characters.
        #expect(payload?.plainText.contains("```") == false)
    }

    @Test func aDiagramSurvivesCharacterForCharacter() {
        let body = "```text\nrepo/\n│\n├── apps/\n└── api/\n```"
        let payload = NoteSharePayload.make(title: nil, body: body)
        for line in ["repo/", "│", "├── apps/", "└── api/"] {
            #expect(payload?.plainText.contains(line) == true, "\(line) did not survive")
            #expect(payload?.html?.contains(line) == true, "\(line) did not survive the rich flavor")
        }
    }

    @Test func aTableTravelsAsATable() {
        // A table keeps its pipe source, which is the **documented** exception (RULES.md §4): a reader
        // never sees pipes on the note's own page, and the pasteboard — and its sibling, the share
        // sheet — still yields the source. That is not storage leaking. It is the one plain-text
        // spelling of a table that stays a table wherever it lands: back in As Told, in anything
        // Markdown-aware, and legibly enough in anything else. Dropping the `| --- |` rule would leave
        // a Markdown table that is no longer a Markdown table.
        let body = "| Day | Plan |\n| --- | --- |\n| Mon | Seward |"
        let payload = NoteSharePayload.make(title: nil, body: body)
        #expect(payload?.plainText == body)
        // `rows` carries the header at [0] and never the `| --- |` rule, so the data row is the last.
        #expect(TableBlock.tables(in: payload?.plainText ?? "").first?.rows.last == ["Mon", "Seward"],
                "the shared text no longer reads back as a table")
        #expect(payload?.html?.contains("Seward") == true)
    }

    // MARK: Encoding

    @Test func everyCharacterSurvivesBothFlavors() {
        let body = "I’m building — this → that\nతెలుగు हिन्दी"
        let payload = NoteSharePayload.make(title: "Café — naïve", body: body)
        for sample in ["I’m", "—", "→", "తెలుగు", "हिन्दी", "Café"] {
            #expect(payload?.plainText.contains(sample) == true, "\(sample) was lost in plain text")
            #expect(payload?.html?.contains(sample) == true, "\(sample) was lost in HTML")
        }
        for garbage in ["â€", "â†", "Ã¢"] {
            #expect(payload?.plainText.contains(garbage) == false)
            #expect(payload?.html?.contains(garbage) == false)
        }
    }

    @Test func theHTMLDeclaresItsEncoding() {
        // The bug this prevents is real: HTML with no declared charset is read back as a legacy
        // single-byte encoding, and every character above ASCII arrives mangled.
        let payload = NoteSharePayload.make(title: nil, body: "Anchorage — Seward")
        #expect(payload?.html?.lowercased().contains("charset=\"utf-8\"") == true)
    }

    @Test func aTitleIsEscapedForHTML() {
        let payload = NoteSharePayload.make(title: "Plans & <notes>", body: "Words")
        #expect(payload?.html?.contains("Plans &amp; &lt;notes&gt;") == true)
        #expect(payload?.html?.contains("<notes>") == false)
    }

    @Test func aTitleIsNotParsedAsANoteLine() {
        // The title is passed to the generator, never prepended to the source. Prepending would run it
        // through `MarkupDocument`, and a title beginning "- " would arrive as a bullet.
        let payload = NoteSharePayload.make(title: "- Trip Plan", body: "Words")
        #expect(payload?.title == "- Trip Plan")
        #expect(payload?.plainText.hasPrefix("- Trip Plan") == true)
        #expect(payload?.html?.contains("<h1>- Trip Plan</h1>") == true)
    }

    // MARK: What the sheet is named

    @Test func theSheetIsNamedByTheTitleWhenThereIsOne() {
        #expect(NoteSharePayload.make(title: "Trip Plan", body: "Anything")?.sheetTitle == "Trip Plan")
    }

    @Test func anUntitledNoteIsNamedByItsFirstLine() {
        // The same stand-in every other surface in the app uses for an untitled note.
        let payload = NoteSharePayload.make(title: nil, body: "Anchorage → Seward\nthen Denali")
        #expect(payload?.sheetTitle == "Anchorage → Seward")
    }

    // MARK: Sharing changes nothing

    @Test func buildingAPayloadNeverTouchesTheNote() {
        let note = Note(title: "Trip Plan", body: "- Eggs\n| A | B |\n| --- | --- |\n| 1 | 2 |")
        let title = note.title
        let body = note.body
        let updated = note.updatedAt

        _ = NoteSharePayload.make(title: note.title, body: note.body)

        #expect(note.title == title)
        #expect(note.body == body)
        #expect(note.updatedAt == updated, "sharing bumped the note's modification date")
    }

    @Test func thePayloadIsASnapshotAndDoesNotFollowLaterEdits() {
        var body = "Anchorage"
        let payload = NoteSharePayload.make(title: nil, body: body)
        body = "Fairbanks"
        #expect(payload?.plainText == "Anchorage")
        #expect(body == "Fairbanks")
    }

    // MARK: The item the sheet is handed

    @Test func oneItemCarriesBothRepresentations() {
        // One provider, two registrations — not two attachments, which is what puts the note into a
        // message twice.
        let payload = NoteSharePayload.make(title: "Trip", body: "[docs](https://astold.app)")!
        let provider = NoteShareItems.provider(for: payload)
        #expect(provider.registeredTypeIdentifiers.contains(UTType.html.identifier))
        #expect(provider.registeredTypeIdentifiers.contains(UTType.utf8PlainText.identifier))
    }

    @Test func plainTextIsTheProvidersOwnRepresentation() {
        // The item is *built from* the note's text, not merely given a data callback that can produce
        // it. That is what the sheet's native Copy is documented to work with, and Copy did not appear
        // at all while the provider was started empty. HTML stays on the same item, registered after.
        let payload = NoteSharePayload.make(title: nil, body: "[docs](https://astold.app)")!
        let ids = NoteShareItems.provider(for: payload).registeredTypeIdentifiers
        #expect(ids.first == UTType.utf8PlainText.identifier)
        #expect(ids.contains(UTType.html.identifier))
    }

    @Test func theItemLoadsAsAStringAndNotOnlyAsBytes() async throws {
        // The distinction the sheet's Copy turns on. A provider that can only *produce data* for
        // plain text advertises the same type identifier as this one, so the identifiers alone cannot
        // tell the two apart — being loadable as an `NSString` is the part that changed.
        let payload = NoteSharePayload.make(title: "Trip", body: "Anchorage — Seward")!
        let provider = NoteShareItems.provider(for: payload)
        #expect(provider.canLoadObject(ofClass: NSString.self))

        // Crossed back as a `String`: `NSString` is not `Sendable`, so the value is converted inside
        // the callback rather than carried out of it.
        let loaded: String = try await withCheckedThrowingContinuation { continuation in
            _ = provider.loadObject(ofClass: NSString.self) { object, error in
                if let string = object as? NSString { continuation.resume(returning: string as String) }
                else { continuation.resume(throwing: error ?? CocoaError(.fileNoSuchFile)) }
            }
        }
        #expect(loaded == payload.plainText)
    }

    @Test func theProviderHandsBackTheBytesThePayloadDescribes() async throws {
        let payload = NoteSharePayload.make(title: "Trip", body: "Anchorage — Seward")!
        let provider = NoteShareItems.provider(for: payload)

        let plain = try await data(from: provider, as: .utf8PlainText)
        #expect(String(data: plain, encoding: .utf8) == payload.plainText)

        let html = try await data(from: provider, as: .html)
        #expect(String(data: html, encoding: .utf8) == payload.html)
    }

    /// Loads one registered representation. The bytes are what a destination actually receives, so
    /// asserting on them is the only way to know the registration carries the payload rather than
    /// merely claiming the type.
    private func data(from provider: NSItemProvider, as type: UTType) async throws -> Data {
        try await withCheckedThrowingContinuation { continuation in
            provider.loadDataRepresentation(forTypeIdentifier: type.identifier) { data, error in
                if let data { continuation.resume(returning: data) }
                else { continuation.resume(throwing: error ?? CocoaError(.fileNoSuchFile)) }
            }
        }
    }

    @Test func theSheetHeaderIsNamedWithoutInventingAURL() {
        // The obvious way to get a rich header is to hand `LPLinkMetadata` a URL. There is no URL for a
        // local note, and making one up would mean a link to nothing and a network request on behalf of
        // a note that never leaves the device.
        let payload = NoteSharePayload.make(title: "Trip Plan", body: "Anything")!
        let metadata = NoteShareItems.metadata(for: payload)
        #expect(metadata.title == "Trip Plan")
        #expect(metadata.originalURL == nil)
        #expect(metadata.url == nil)
    }
}
